<!--      <section class="sec_cta ">
        <div class="container">
          <div class="">
            <div class="cta_inner wow rubberBand">
              <h2 class="heading">We Help You Ace Your Career by Registering You On The World's Most Trusted Referral Portals </h2>
              <div class="button">
                <a class="btn-org fill" href="tel:844-640-8881"><i class="fa fa-phone" aria-hidden="true"></i> &nbsp;
                844-640-8881</a>
                <a href="javascript:;" onclick="buttonURL();" class="btn-org btn-white fill"> <i class="fa fa-commenting-o" aria-hidden="true"></i> &nbsp;
                Live Chat</a>
                <a class=" btn_green fill" href="https://wa.me/+1-415-329-179981" target="_blank" style="">
                <i class="fa fa-whatsapp" aria-hidden="true"></i> &nbsp; Whatsapp</a>
                <a href="skype:cid.6430c728aa5b64f?call" class="btn_skyb  fill" style=""> <i class="fa fa-skype" aria-hidden="true"></i> &nbsp; Skype</a>
              </div>
            </div>
          </div>
        </div>
      </section>-->
      <section class="sec_testimonials">
        <div class="container">
          <div class="row">
            <div class="testimonials_inner">
              <div class="col-md-12">
                <h2 class="heading wow rubberBand">Client Testimonials</h2>
                <div class="col-md-6">
                  <div class="testimonials_box_l wow bounceInLeft">
                    <div>
                      <img src="<?php echo $theme_url;?>assets/images/testimonials_icon.png">
                      <i class="fa fa-quote-right"></i>
                      <p>I really appreciate the time taken and approach by the team. My new resume, LinkedIn Bio, Cover Letter and Bio have already opened multiple doors of opportunity. Thank you so much for your amazing CV and resume services</p>
                      <h4>Joshua Kennedy</h4>
                    </div>
                    <div>
                      <img src="<?php echo $theme_url;?>assets/images/testimonials_icon.png">
                      <i class="fa fa-quote-right"></i>
                      <p>What a fantastic experience. I spoke to their team, and they put my resume together in such a fantastic way that the resume seemed concise, all-inclusive and focused. Previously I struggled with what information to include and how to express what I did in my resume, but with the services provided by What A Resume Online. I was able to secure the job of my dreams and jump-start my career successfully</p>
                      <h4>Rhona Williams</h4>
                    </div>
                    <div>
                      <img src="<?php echo $theme_url;?>assets/images/testimonials_icon.png">
                      <i class="fa fa-quote-right"></i>
                      <p>My experience with What A Resume Online. was productive, seamless and efficient. As a professional salesperson, I am so thankful to have their service as I would not have been able to create such an effective resume without their guidance and expertise. The team at What A Resume Online. is impressive and well-versed in the art of resume and CV writing.</p>
                      <h4>Alan P. Wills</h4>
                    </div>
                    <div>
                      <img src="<?php echo $theme_url;?>assets/images/testimonials_icon.png">
                      <i class="fa fa-quote-right"></i>
                      <p>The service I received from What A Resume Online. was a truly professional and delightful experience. I would recommend them to anyone looking to have a resume done to obtain that dream job</p>
                      <h4>Nance Jones</h4>
                    </div>
                  </div>
                </div>
                <div class="col-md-6  wow bounceInRight">
                  <a class="right_img_trust">
                    <!-- <img src="<?php echo $theme_url;?>assets/images/trust-imggg.png"> -->
                    <!-- Image Map Generated by http://www.image-map.net/ -->
                    <img src="<?php echo $theme_url;?>assets/images/trust-imggg.png">
                  </a>
                </div>
              </div>
              <!-- <div class="col-md-4">
                <h2 class="heading">Rewards And Recognitions</h2>
                <div class="testimonials_box_r">
                	<img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon1.jpg">
                	<img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon2.jpg">
                	<img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon3.jpg">
                	<img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon4.jpg">
                	<img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon5.jpg">
                	<img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon6.jpg">
                </div>
                </div> -->
            </div>
          </div>
        </div>
      </section>
      <section class="vid_testimonial">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <div class="vid-hd-txt">
                <h2 class="heading wow rubberBand">Video Testimonials</h2>
              </div>
            </div>
            <div class="col-sm-12">
              <div class="col-sm-6">
                <div class="video-testi-img vid-tst-1">
                  <a href="embed/utTy0KQ4D_g.html" class="fancybox" rel="ligthbox" tabindex="0">
                    <img src="<?php echo $theme_url;?>assets/images/vtesti-img1.png">
                    <div class="box-content">
                      <img src="<?php echo $theme_url;?>assets/images/vplay-icon.png">
                    </div>
                  </a>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="video-testi-img vid-tst-2">
                  <a href="embed/c5xOE1_Kb8g.html" class="fancybox" rel="ligthbox" tabindex="0">
                    <img src="<?php echo $theme_url;?>assets/images/vtesti-img2.png">
                    <div class="box-content">
                      <img src="<?php echo $theme_url;?>assets/images/vplay-icon.png">
                    </div>
                  </a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      <div class="trsut-seals wow rubberBand">
        <div class="container">
          <h2 class="heading">Rewards And Recognitions</h2>
          <div class="col-reviews-certificate"> <img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon1.jpg" class="img-responsive" alt="The Best Reviews"> </div>
          <div class="col-reviews-certificate"> <img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon2.jpg" class="img-responsive" alt="Comprehensive Reliability"> </div>
          <div class="col-reviews-certificate"> <img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon3.jpg" class="img-responsive" alt="Citation Checker"> </div>
          <div class="col-reviews-certificate"> <img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon4.jpg" class="img-responsive" alt="Approved by Editors &amp; Proofreaders"> </div>
          <div class="col-reviews-certificate"> <img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon5.jpg" class="img-responsive" alt="100% Satisfaction Guaranteed"> </div>
          <div class="col-reviews-certificate"> <img src="<?php echo $theme_url;?>assets/images/reviews_badges_icon6.jpg" class="img-responsive" alt="100% Satisfaction Guaranteed"> </div>
        </div>
      </div>
      <section class="section-padding gray_bg get_quote">
        <div class="container">
          <div class="row">
            <div class="col-md-push-2 col-md-8">
              <h4 class="heading wow rubberBand">The Fastest Way to Land your <br>Next Job is Here</h4>
              <form method="POST" action="mail.php" id="quoteForm">
                 <?php include "views/lead.php" ?>
              </form>
            </div>
            <!-- end col-md-6 -->
          </div>
          <!-- end row -->
        </div>
        <!-- end container -->
      </section>

<footer class="sec_footer" style="background:#5050ff">
      <div class="container">
        <div class="row">
          <div class="footer_boxes">
            <div class="col-sm-4">
              <div class="footer_box">
                <h3 class="footer_title">About</h3>
                <p>We are one of the most impressive resume and CV writing services providers in the market. Recommended by thousands of clients, recruiting agencies, candidates, professionals and HR experts, Our mission is to considerably increase our clients' resume's response rate while making it professional and accurate.</p>
                <a href="javascript:;" class="btn-org various fill  viewMain" tabindex="-1" onclick="order_now_value(this)" name="for $149">Get Started</a>
              </div>
            </div>
            <div class="col-sm-3 ">
              <div class="footer_box">
                <h3 class="footer_title">Services</h3>
                <ul>
                  <li><a href="<?php echo base_url(); ?>resume-writing"><i class="fa fa-check"></i> Resume Writing Services</a></li>
                  <li><a href="<?php echo base_url(); ?>cover-letter-writing"><i class="fa fa-check"></i> Cover Letters Writing</a></li>
                  <li><a href="<?php echo base_url(); ?>linkedin-profile-writing"><i class="fa fa-check"></i> LinkedIn Profile Writing</a></li>
                  <li><a href="<?php echo base_url(); ?>career-coaching-service"><i class="fa fa-check"></i> Career Coaching Service</a></li>
                  <li><a href="<?php echo base_url(); ?>job-profiling"><i class="fa fa-check"></i> Job Profiling</a></li>
                  <li><a href="<?php echo base_url(); ?>webpage-resume"><i class="fa fa-check"></i> Webpage Resume</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-2">
              <div class="footer_box">
                <h3 class="footer_title">Company</h3>
                <ul>
                  <li><a href="<?php echo base_url(); ?>about-us.php"><i class="fa fa-check"></i> How We Work</a></li>
                  <li><a href="<?php echo base_url(); ?>contact-us.php"><i class="fa fa-check"></i> Contact</a></li>
                  <li><a href="<?php echo base_url(); ?>resume-samples"><i class="fa fa-check"></i> Resume Samples</a></li>
                  <li><a href="<?php echo base_url(); ?>pricing"><i class="fa fa-check"></i> Pricing</a></li>
                  <li><a href="<?php echo base_url(); ?>reviews"><i class="fa fa-check"></i> Reviews</a></li>
                </ul>
              </div>
            </div>
            <div class="col-sm-3">
              <div class="footer_box">
                <h3 class="footer_title">Contact Us</h3>
                <ul>
                  <li><a href="tel:844-640-8881">Direct Line: 844-640-8881</a></li>
                  <li><a href="cdn-cgi/l/email-protection.html#f79e999198b7859284829a928785989184d994989a"><span class="__cf_email__" data-cfemail="157c7b737a5567706660787065677a667a7b797c7b703b767a78">[email&#160;protected]</span></a></li>
                </ul>
                <h3 class="footer_title payment-methods"> Our Secure Payment Methods </h3>
                <img src="<?php echo $theme_url;?>assets/images/payment-icon2.png" class="img-responsive">
                <h3 class="footer_title payment-methods">Follow Us</h3>
                <ul class="social_icon_footer">
                  <li><a href="Resumeprosonlineofficial/index.htm?modal=admin_todo_tour" target="_blank"><i class="fa fa-facebook"></i></a></li>
                  <li><a href="https://www.trustpilot.com/review/resumeprosonline.com" target="_blank"><img class="bar_icon" src="<?php echo $theme_url;?>assets/images/trustpilot.png"></a></li>
                  <li><a href="en/us/company/resume-pros-online/d7yaY/index.htm" target="_blank"><img class="bar_icon" src="<?php echo $theme_url;?>assets/images/bar.png"></a></li>
                  <li><a href="company-reviews/store/resumeprosonline-com.html" target="_blank"><img class="bar_icon" src="<?php echo $theme_url;?>assets/images/rev.png"></a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <footer class="footer_bottom">
      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <p>Copyright 2021. What A Resume Online All Rights Reserved.</p>
            <!--<ul>
              <li><a href="#">Privacy Policy</a></li>
              <li><a href="#">Terms & Conditions</a></li>
            </ul>-->
          </div>
        </div>
      </div>
    </footer>

    <div class="black-layout"></div>
    <div class="popup popup_new_form  mainPop viewPop">
      <a class="popup-close" href="javascript:;">
      <i class="fa fa-times" aria-hidden="true"></i>
      </a>
      <div class="row popWrap">
        <div class="col-md-6 pad-r-zero">
          <img src="<?php echo $theme_url;?>assets/images/pop-img.jpg" alt="">
        </div>
        <div class="col-md-6 pad-l-zero">
          <form id="quoteForm" method="POST" action="mail.php">
            <div class="formWrap">
              <div class="popup-header">
                <h4>Get A <span>Resume</span> that <br>Acess All HR Standards.</h4>
              </div>
              <div class="popup-bdy">

                <script charset="utf-8" type="text/javascript" src="//js.hsforms.net/forms/shell.js"></script>
                <script>
                  hbspt.forms.create({
                	region: "na1",
                	portalId: "19966912",
                	formId: "59589bf1-c6bf-4301-a346-b414981b45e8"
                });
                </script>

              </div>
              <!-- <span class="uptownloader"></span> -->
            </div>

          </form>
        </div>
      </div>
    </div>
    <script src="<?php echo $theme_url;?>assets/js/jquery-1.10.2.min.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/bootstrap.min.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/chat.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/wow.min.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/fancybox.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/slick.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/accordian-jquery-ui.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/owl.carousel.min.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/bootstrap-popover-custom-class.js"></script>
    <script src="<?php echo $theme_url;?>assets/js/custom.js"></script>

    <!-- Start of HubSpot Embed Code -->
    <script type="text/javascript" id="hs-script-loader" async defer src="//js.hs-scripts.com/19966912.js"></script>
    <!-- End of HubSpot Embed Code -->

    <script>

    function buttonURL(){
    window.HubSpotConversations.widget.open();
    }

      function order_now_value(objButton){
                    x = objButton.name;
                    document.getElementById('lead_area_popup').value = x;
                    document.getElementById('lead_text').innerHTML = x;
                }

      $(document).ready(function() {
                  //var currentIP;
                  var key = '5XpThOAEkfgOvEJ';

                  var currentIP = $("meta[name=ip2loc]").attr('content');
                  var pgurl = $("meta[name=page_url]").attr('content');
                  $.ajax({
                      method: 'get',
                      url: '//pro.ip-api.com/json/' + currentIP,
                      data: {
                          key: key
                      },
                      success: function(data) {
                          if (data) {
                              $('input[name=ip2loc_ip]').val(data.query);
                              $('input[name=ip2loc_isp]').val(data.isp);
                              $('input[name=ip2loc_org]').val(data.org);
                              $('input[name=ip2loc_country]').val(data.country);
                              $('input[name=ip2loc_region]').val(data.regionName);
                              $('input[name=ip2loc_city]').val(data.city);
                              $('input[name=pageurl]').val(pgurl);
                          }
                      }
                  });
              });

      $( function() {
            $( "#accordion1" ).accordion();
         } );

      $( function() {
            $( " #accordion2" ).accordion();
         } );

      $( function() {
            $( "#accordion3" ).accordion();
         } );


      $('#service-category-tabs li a').click(function(){

          $('#service-category-tabs li a').find('i').removeClass('fa-chevron-up').addClass('fa-chevron-down');

        if($(this).next('.contant_box_acc').css('display')=='block') {

          $(this).next('.contant_box_acc').slideUp('slow');

        }else{

          $('#service-category-tabs .contant_box_acc').css('display','none');

          $(this).next('.contant_box_acc').slideDown('slow');

          $(this).find('i').toggleClass('fa-chevron-down fa-chevron-up');

        }



      });


      var a = 0;
            $(window).scroll(function() {

              var oTop = $('#counter').offset().top - window.innerHeight;
              if (a == 0 && $(window).scrollTop() > oTop) {
                $('.counter-value').each(function() {
                  var $this = $(this),
                    countTo = $this.attr('data-count');
                  $({
                    countNum: $this.text()
                  }).animate({
                      countNum: countTo
                    },

                    {

                      duration: 2000,
                      easing: 'swing',
                      step: function() {
                        $this.text(Math.floor(this.countNum));
                      },
                      complete: function() {
                        $this.text(this.countNum);
                        //alert('finished');
                      }

                    });
                });
                a = 0;
              }

            });

            /* POPUP Main */

          $('.viewMain').click(function() {
              $('.viewPop').fadeIn();
              $('.black-layout').fadeIn();
          });

          $('.viewLeadPop').click(function() {
              $('.viewPop').fadeIn();
              // $('.LeadPop').fadeIn();
              $('.black-layout').fadeIn();
          });

          /* Header Height */
          // $('.hdr-space').height($('.header').height());



          /* Close POPUP */
          $('.popup-close,.black-layout').click(function() {
              $('.viewPop').fadeOut();
              $('.black-layout').fadeOut();
          });


          $('.home_title_slider').slick({
            dots: false,
            infinite: true,
            autoplay:true,
            autoplaySpeed:2500,
            arrows: false,
            speed: 2500,
            fade:true,
            slidesToShow: 1,
            slidesToScroll: 1,
            responsive: [
              {
                breakpoint: 1024,
                settings: {
                  slidesToShow: 1,
                  slidesToScroll: 1,
                  infinite: true,
                  dots: true
                }
              },
              {
                breakpoint: 600,
                settings: {
                  slidesToShow: 1,
                  slidesToScroll: 1
                }
              },
              {
                breakpoint: 480,
                settings: {
                  slidesToShow: 1,
                  margin:0,
                  slidesToScroll: 1
                }
              }
            ]
          });
    </script>
    <script type="text/javascript">
      function t() {
          e($(".cd-headline.letters").find("b")), s($(".cd-headline"))
      }

      function e(t) {
          t.each(function() {
              var t = $(this),
                  e = t.text().split(""),
                  s = t.hasClass("is-visible");
              for (i in e) t.parents(".rotate-2").length > 0 && (e[i] = "<em>" + e[i] + "</em>"), e[i] = s ? '<i class="in">' + e[i] + "</i>" : "<i>" + e[i] + "</i>";
              var n = e.join("");
              t.html(n).css("opacity", 1)
          })
      }

      function s(t) {
          var e = c;
          t.each(function() {
              var t = $(this);
              if (t.hasClass("loading-bar")) e = u, setTimeout(function() {
                  t.find(".cd-words-wrapper").addClass("is-loading")
              }, p);
              else if (t.hasClass("clip")) {
                  var i = t.find(".cd-words-wrapper"),
                      s = i.width() + 10;
                  i.css("width", s)
              } else if (!t.hasClass("type")) {
                  var o = t.find(".cd-words-wrapper b"),
                      r = 0;
                  o.each(function() {
                      var t = $(this).width();
                      t > r && (r = t)
                  }), t.find(".cd-words-wrapper").css("width", r)
              }
              setTimeout(function() {
                  n(t.find(".is-visible").eq(0))
              }, e)
          })
      }

      function n(t) {
          var e = l(t);
          if (t.parents(".cd-headline").hasClass("type")) {
              var i = t.parent(".cd-words-wrapper");
              i.addClass("selected").removeClass("waiting"), setTimeout(function() {
                  i.removeClass("selected"), t.removeClass("is-visible").addClass("is-hidden").children("i").removeClass("in").addClass("out")
              }, v), setTimeout(function() {
                  o(e, m)
              }, g)
          } else if (t.parents(".cd-headline").hasClass("letters")) {
              var s = t.children("i").length >= e.children("i").length ? !0 : !1;
              r(t.find("i").eq(0), t, s, f), a(e.find("i").eq(0), e, s, f)
          } else t.parents(".cd-headline").hasClass("clip") ? t.parents(".cd-words-wrapper").animate({
              width: "2px"
          }, y, function() {
              d(t, e), o(e)
          }) : t.parents(".cd-headline").hasClass("loading-bar") ? (t.parents(".cd-words-wrapper").removeClass("is-loading"), d(t, e), setTimeout(function() {
              n(e)
          }, u), setTimeout(function() {
              t.parents(".cd-words-wrapper").addClass("is-loading")
          }, p)) : (d(t, e), setTimeout(function() {
              n(e)
          }, c))
      }

      function o(t, e) {
          t.parents(".cd-headline").hasClass("type") ? (a(t.find("i").eq(0), t, !1, e), t.addClass("is-visible").removeClass("is-hidden")) : t.parents(".cd-headline").hasClass("clip") && t.parents(".cd-words-wrapper").animate({
                  width: t.width() + 10
              }, y, function() {
                  setTimeout(function() {
                      n(t)
                  }, w)
              })
      }

      function r(t, e, i, s) {
          if (t.removeClass("in").addClass("out"), t.is(":last-child") ? i && setTimeout(function() {
                      n(l(e))
                  }, c) : setTimeout(function() {
                  r(t.next(), e, i, s)
              }, s), t.is(":last-child") && $("html").hasClass("no-csstransitions")) {
              var o = l(e);
              d(e, o)
          }
      }

      function a(t, e, i, s) {
          t.addClass("in").removeClass("out"), t.is(":last-child") ? (e.parents(".cd-headline").hasClass("type") && setTimeout(function() {
              e.parents(".cd-words-wrapper").addClass("waiting")
          }, 200), i || setTimeout(function() {
              n(e)
          }, c)) : setTimeout(function() {
              a(t.next(), e, i, s)
          }, s)
      }

      function l(t) {
          return t.is(":last-child") ? t.parent().children().eq(0) : t.next()
      }

      function h(t) {
          return t.is(":first-child") ? t.parent().children().last() : t.prev()
      }

      function d(t, e) {
          t.removeClass("is-visible").addClass("is-hidden"), e.removeClass("is-hidden").addClass("is-visible")
      }
      var c = 1e3,
          u = 2e3,
          p = u - 3e3,
          f = 50,
          m = 150,
          v = 250,
          g = v + 250,
          y = 200,
          w = 500;
      t()

    </script>
  </body>
</html>